name: tshirt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  animated_background: ^2.0.0
  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.0.0
flutter_animate: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  

flutter:
  uses-material-design: true
